### ISSUE TITLE
Vera Thermostat not reporting correct heat setpoint state in DeviceInfo area

### ISSUE THREAD

**Issue by htcheng** [pavoni/pyvera#102]
I have two different model zwave thermostats (Trane and Honeywell) connected to Vera and pyvera is incorrectly reporting the "heat" setpoint for both of these devices when the thermostats run their internal schedulers. Vera is showing the correct information for both thermostats, but when pyvera parses the state information, it is not correctly parsing the returned values. I suspect this is because "CurrentSetpoint" is used as the variable name for 3 different state variables internally (see XML below).

[veraxml.pdf](https://github.com/pavoni/pyvera/files/2612073/veraxml.pdf)

My python is pretty rudimentary but I've traced back the source of the problem to how the subscription registry updates the state information. Using pyvera's function 

get_complex_value("CurrentSetpoint") directly from the controller returns the correct values for both thermostats' heat setpoint, but querying the state info from the subscription registry yields incorrect values:

>>> devices
[VeraThermostat (id=37 category=Thermostat name=Upstairs Temp), VeraArmableDevice (id=37 category=Thermostat name=Upstairs Temp), VeraThermostat (id=55 category=Thermostat name=Downstairs Temp)]
>>> devices[0].get_complex_value("CurrentSetpoint")
'66.00'
>>> devices[2].get_complex_value("CurrentSetpoint")
'69.00'
>>> devices[0].get_all_values()
{'name': 'Upstairs Temp', 'altid': '19', 'id': 37, 'category': 5, 'subcategory': 1, 'room': 0, 'parent': 1, 'fanmode': 'Auto', 'hvacstate': 'Idle', 'mode': 'HeatOn', **'setpoint': '78.00', 'heat': '78.00'**, 'cool': '78.00', 'status': '0', 'commFailure': '0', 'lasttrip': '1527243354', 'tripped': '0', 'armed': '0', 'armedtripped': '0', 'temperature': '70.00', 'state': -1, 'comment': '', 'categoryName': 'Thermostat'}
>>> devices[2].get_all_values()
{'name': 'Downstairs Temp', 'altid': '35', 'id': 55, 'category': 5, 'subcategory': 1, 'room': 0, 'parent': 1, 'fanmode': 'Auto', 'hvacstate': 'Idle', 'mode': 'HeatOn', 'temperature': '69.00', **'setpoint': '78.00', 'heat': '78.00'**, 'cool': '78.00', 'status': '0', 'light': '0.2', 'state': -1, 'comment': '', 'categoryName': 'Thermostat'}

Looking at the information above, I believe that the subscription registry should be using the variable "AllSetpoints" from Vera and parse the first two numbers (heat, cool) to set the correct state information for Vera thermostats rather than using "CurrentSetpoint" which will set the 'setpoint' and 'heat' states to the 'cool' state since they all use the same variable name 'CurrentSetpoint' (how stupid is that?).

I'd make this change, but I'm still brushing up my python... if I can figure out a solution, I'll update it here, but any help would be appreciated...

**Comment by htcheng** [comment]
[veraxml.pdf](https://github.com/pavoni/pyvera/files/2612066/veraxml.pdf)

**Comment by htcheng** [comment]
Hmm. I think I found an easier solution to the issue by modifying the following:

def get_current_goal_temperature(self, refresh=False):
        """Get current goal temperature / setpoint"""
        if refresh:
            self.refresh()
        try:
            **return float(self.get_complex_value('CurrentSetpoint'))**
        except (TypeError, ValueError):
            return None

**Comment by htcheng** [comment]
The above solution works for me...

**Comment by pavoni** [comment]
Sorry to hear about the issue. I don't have a thermostat - so I need to be very careful about changes there. 

Mostly the vera code tries to get state info via subscription, that means that it doesn't need to call vera every time a variable value is requested - and that HA states update in real time.

`get_complex_value` bypasses this mechanism - so should only be used, with care, where there isn't an alternative. So the ideal would be to find a way to get the info you need via the state mechanism.

There were also some complexities about how heat only and heat cool thermostats work - which caused us problems previously.

@alanfischer is the expert here - so may be able to help.

**Comment by htcheng** [comment]
Thanks, Greg. I think that using the ‘AllSetpoints' variable to set the devinfo state is probably the way to go, since it seems to be universal across different thermostats and actually includes the range of heat/cool set points. I don’t know if this is actually true with heat only thermostats, but seems to be true across the Trane and Honeywell thermostats I’ve seen.

It’s strange that Vera or the devices assign the same variable ‘CurrentSetpoint' to the three values in the XML/JSON response. I saw that the Nest.py thermostat under Climate allows the heat/cool set points as a range in their Home Assistant component implementation so that when “Auto” was set, it would automatically set the correct range of set points using an upper/lower bound. Perhaps this could be implemented in the Vera implementation as well.

I just noticed that the DevInfo state for both thermostats' fan modes is also reflecting ‘auto’ when both are actually set to ‘heat’ mode - I’ll double-check this and open up another bug report if this warrants it.

My solution was a hack so that Home Assistant and Homekit would at least report the right temperature set point in my set up - it was driving me crazy that every time the thermostats’ own scheduler switched program settings, Home Assistant (and thus Homekit via the bridge) would report the Cooling set point and not the correct heating set point. I use the thermostats’ own schedulers as a backup to make sure at least the heating comes on/turns off if Home Assistant or Vera die on me.

**Comment by toggledbits** [comment]
I'm the developer of three thermostat interfaces/plugins for Vera (IntesisBox, Venstar ColorTouch, and AutoVirtualThermostat). Vera's handling of temperature setpoint vs UPnP is gawd awful (well, it's awful at everything, but that's another thread). Unfortunately, AllSetpoints is not to be trusted--it isn't even declared in any of UPnP's standards or Vera's extension service declaration files, it just magically appears on the devices that support it, which is not all.

In the Vera world, the most "typical" way of handling setpoints is Vera's corruption of the UPnP standard for the service urn:upnp-org:serviceId:TemperatureSetpoint1. They apparently could not figure out how to properly use UPnP's "SetApplication" mechanism, so they ignore it and create two additional services with similar names: TemperatureSetpoint1_Heat and TemperatureSetpoint1_Cool, and within those, the SetCurrentSetpoint action (parameter NewCurrentSetpoint) sets the temperature setpoint type that matches the suffix they added. The state variable CurrentSetpoint in each service holds the current value.

IMO, the more reliable way to get the current setpoints is to query each of these services for their CurrentSetpoint values. Failing that, the first fallback is the CurrentSetpoint in the plain/standard TemperatureSetpoint1 service (no _Heat/_Cool suffix), and then finally AllSetpoints if the thermostat has it.

The challenge here will be that those are not available in sdata (used by the polling loop), because there is no standard shortcode for all devices. Vera's version of the TemperatureSetpoint1 service declares a "setpoint" shortcode, but because they use the same service twice (and in some cases three times) to create their virtual services _Heat and _Cool, the value of one is overwritten by the other, not duplicated, in sdata responses. They've made a fine mess. So, the only way to get the real, honest values is to get them from UserData.

Greg, I think this points to a bigger shortcoming in the current polling loop that I've touched on before--because the polling loop uses sdata rather than userdata, with the former being a subset of device state, a LOT of data changes are missed by the current loop, and a bunch of data, including these setpoint values, is harder to get at. I'll open a separate issue to continue discussion on that.

**Comment by toggledbits** [comment]
> It’s strange that Vera or the devices assign the same variable ‘CurrentSetpoint' to the three values in the XML/JSON response.

It's not the same variable. In the Vera/UPnP world, a variable is identified by its name _and a serviceId_. If you see more than one variable with the same name in the Vera UI, it's because each is in a different service. See my previous above for why you seem to have three "CurrentSetpoint" variables.

**Comment by GaryOkie** [comment]
Hi @toggledbits ,

Regarding your comment

>  I'm the developer of three thermostat interfaces/plugins for Vera (IntesisBox, Venstar ColorTouch, and AutoVirtualThermostat). 

I am wondering if by changing out my Zwave therm0stats that are currently controlled by Vera, to a Venstar Touch wifi,  would this nasty problem of showing the wrong setpoint in HA go away?

This bug wasn't an issue in the summer (cool mode), but now that the T-stats are in Heat mode, showing the cooling setpoint insted of heat setpoint in HA is just unacceptable.  Since there doesn't  seem to be any hope of it being fixed, I am now looking at replacing all my T-stats if you would be able to confirm if your Venstar Vera interface would solve it with HA.   

I had another thought - could your Vera auto virtual thermostat be used to trigger the CT100 ZWave heat/cool settings, and if so, would that Virtual Tstat solve the setpoint communication problems between Vera and HA?

**Comment by GaryOkie** [comment]
I've replaced my Zwave thermostats with Venstar T7850's and first tried @togglebits Vera plugin.   It works very nicely - for the Vera UI.   But via HA/pyvera it has the exact same problem reporting an incorrect heat setpoint.    This should have been expected, and a bit naive of me to think there may have been a workaround at the plugin level.

So while I continue to rely on a VeraPlus hub to manage all my Zwave devices and security panel, thermostats will no longer be among them.

**Comment by alanfischer** [comment]
@GaryOkie I use pyvera for my CT101 and it works for both heat & cool fine.  I might be able to assist with a fix for this.  Or at least, I can attempt to make changes and verify that it doesn't break what currently is working.  Are you able to build a custom pyvera and see if the solution that @htcheng originally posted works, aside from the device info area?

**Comment by GaryOkie** [comment]
Hi @alanfischer  - After reading the caution from Greg/@pavoni about get_complex_value bypassing normal pyvera subscription behavior, and Patrick's/@toggledbits detailed info, I decided to just wait until the next heating season hoping there would be a permanent fix (not an iffy hack) in the meantime.    

Well, a year later I could have gone with the custom local fix and try to keep up with all the other pyvera updates manually.     Instead I decided to just go with new thermostats  that did not need to rely on Vera Zwave and pyvera support.   (Not to mention, a much improved color touch screen).

I really appreciate your offer to make changes to pyvera, but it's a bit too late for me for this specific issue.    BTW - I'm still using using the CT100 T-Stats - but as remote temperature/humidity monitoring stations only.

**Comment by pavoni** [comment]
There are limits in both Vera and pyvera here.

The former is no longer sold (and development seems to be frozen).

I suspect new zwave users will pick another approach - so the main aim is to keep pyvera stable and working.

So closing for now.

**Comment by GaryOkie** [comment]
Greg,  

Not that it matters, but to clarify - Vera Secure Hubs  are still being sold directly by Ezlo.  The Vera Mios firmware is still receiving support, but not so much anymore.   There was supposed to be at least one more firmware fix release coming.  

The big push from EzLo is their new hubs running a new Linux-based OS.   This OS is also available on older [Vera Edge hubs in Beta](https://community.getvera.com/t/beta-ezlo-linux-v-2-0-3-1159-2-for-ezlo-plus-and-vera-edge/215746).   pyvera won't be usable since API backward compatibility is surely off the table.

I don't disagree that many users will (and have) migrated away from Vera, but as a dedicated ZWave/Zigbee hub, it has been very stable with HASS+pyvera doing all the heavy lifting.

**Comment by pavoni** [comment]
Thanks Gary - much better that I thought - thanks.

I'm still using mine which works well. I just fixed a small bug in the home assistant wrapper https://github.com/home-assistant/core/pull/45535

As you say as a HA interface it's stable - although new device support leave a lot to be desired!

**Comment by GaryOkie** [comment]
And thank YOU for fixing that issue!    It's much appreciated that you still look after this code's maintenance.

**Comment by databoy2k** [comment]
Requesting a re-open if possible; This stupid bug is still here and kind of irritating since it makes HA report the entirely wrong setpoint. Can we not choose urn:upnp-org:serviceId:TemperatureSetpoint1 / CurrentSetpoint to report, rather than urn:upnp-org:serviceId:TemperatureSetpoint1_Cool / CurrentSetpoint or urn:upnp-org:serviceId:TemperatureSetpoint1_Heat / CurrentSetpoint

**Comment by htcheng** [comment]
Yes, it's even worse as now even my Trane thermostat that used to report the correct values is showing the incorrect values...

**Comment by GaryOkie** [comment]
@htcheng - as I recall, toggledbits basically predicted your original setpoint hack/workaround would not be correct all the time, which is the case with the production pyvera as well. 

Toggledbits also provided a very detailed reply about what it would take to fix this.  In a nutshell, pyvera would have to be modified to poll the very verbose data stream of "userdata" instead of the short and sweet "sdata" since that was the only way to obtain the proper values.   No telling what knock on effects that might have with stability.

Given the aging state of Vera/Mios, its frozen firmware and push by Ezlo to get users onto new hubs, there is not much interest in taking a stab at fixing this legacy hub that could cause unpredictable stability issues.

I have long since added a Zwave stick to my HA systems, carefully migrating each device one by one.   The Zwave-JS support in HA is excellent.    I am only using Vera now as for serial connections to a security system, along with pyvera to return binary status of each sensor.

**Comment by databoy2k** [comment]
> Given the aging state of Vera/Mios, its frozen firmware and push by Ezlo to get users onto new hubs, there is not much interest in taking a stab at fixing pyvera for this legacy hub that could cause unpredictable stability issues.

Respectfully, and despite being the type of person who shouldn't be charged with the PR for exactly this reason, I don't think the correct answer should be "this library is hopelessly broken due to the device being obsolete and apparently designed by morons." The code freeze and lack of future device compatibility should mean that we can staple workarounds onto it now without fear that they'll cause issues in the future. 

Is it possible to implement the userdata stream as a selectable, non-default, option for development purposes? Maybe have the flag in the configflow of Home Assistant, for example. It would also mean that we can test the changes with a wider range of users (potentially) and get additional feedback on whether it breaks something else.

I guess I'm not wanting to see the project just die because this project is probably all that's keeping a bunch of veras from becoming e-waste. If there's an alternative project that might actually work better, and heaven forbid doesn't need to be coded with future unknown devices in mind (since the firmware is unlikely to add any support for anything new), it might be worth fixing it up.

**Comment by pavoni** [comment]
I’m afraid I no longer have a live Vera hub. So I’d be very reluctant to release changes to the repo that I can’t test.

So unless someone wants to take over, I’m afraid the repo is really frozen.

I haven’t archived because I think people still depend on the existing functionality.

Like some others here I’ve moved to zwave-is which is very good and well supported.
