### ISSUE TITLE
Vera 7.3 firmware Beta & pyvera

### ISSUE THREAD

**Issue by GaryOkie** [pavoni/pyvera#121]
Does anyone who relies on or maintains pyvera plan on participating in the [Vera 7.3 core firmware Beta](https://community.getvera.com/t/vera-7-30-core-firmware-beta-release/210665) testing?

This would be a great opportunity to not just get a jump on any potential backwards compatibility issues but also to provide input on improving the API.

This firmware update is quite massive in content, and provides major improvements for system reliability.   I don't have a spare system to be able to test but am really looking forward to the upgrade - provided pyvera has been actively tested with it.

**Comment by pavoni** [comment]
Hi @GaryOkie - as you'll have seen - this isn't the most active repo around. I think it's mainly because it generally works well enough for the basic cases that most of us use.

I would certainly welcome an active participant interested in doing what you suggest.

I have to confess that I mostly leave my vera firmware as it is (having had some issue upgrading in the past) - since for me it seems very stable.

**Comment by GaryOkie** [comment]
Just installed the Vera 7.31 production firmware.   It's working quite well, but am concerned about a new error I'm seeing in the pyvera/HA integration.   Someone else just posted about a thermostat problem so it does appear that this update may require further investigation.    I'll close this and raise a new issue with the new _ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device_   - _AttributeError: 'NoneType' object has no attribute 'add_job'_
