### ISSUE TITLE
Some switches don't update state

### ISSUE THREAD

**Issue by pavoni** [pavoni/pyvera#51]
In some cases changing a switch isn't updating the state in pyvera.

**Comment by alanthewild** [comment]
Hi @pavoni 

I have this same issue with one of my light switches only - A Fibaro FG223.
I'm running HA v0.45 with the Pyvera debug level logging turned on.
I'm using a Fibaro FGS-223 - Double Switch 2 - which has two circuits/channels. The primary/master works happily. The secondary doesn't if you use the switch itself and not Vera/HA or one of the apps/software switches.

Behaviour when using different methods for turning on the light:
If I use HA to turn it on/off, I get several lines of HA logs relating to the switch and the state is correct. 
If I use the AppDaemon dashboard, I get several lines in the HA logs and the state is correct.
If I use Vera to turn it on, I get several lines in the HA logs and the state is correct.
If I use the switch on the wall, I get nothing in the logs at all and the state doesn't change but the physical light state changes.

I don't think this is a problem with HA at all (for me at least).
I think it's an issue with the way Vera is communicating with this specific switch model.
As the Fibaro FGS223 is not officially supported by Vera at this point and I had to tweak it to get it to work, I believe the issue is that the tweaking is clearly not 100% right.... 

Switch configured using the info from this forum: http://forum.micasaverde.com/index.php/topic,38961.0.html

**Comment by pavoni** [comment]
Might be worth adding some debug logging to your HA set-up

````
logger:
  logs:
      pyvera: debug
````

This shows the messages we get from vera - pyvera ignores some of them - so it's possible there is some info we're missing.

This logs everything -so can be a lot of data.

**Comment by alanthewild** [comment]
That was with the Pyvera debugging on. 
Nothing in the logs at all as the secondary switch state change doesn't appear in Vera so will never appear in HA. Vera state is wrong and HA state just mirrors Vera state.

So I think it's definitely a Vera issue for me.
Going to see what debugging I can get on the Vera side of things to see what's going on.
Alternatively, if Vera get around to officially supporting the Fibaro module, the issue may go away.

**Comment by pavoni** [comment]
Thanks for digging. As you say - if it's not correct in Vera there's not we can do until they fix it!

Will leave this open, since the other case sounds like some sort of race condition with older switches.

**Comment by pavoni** [comment]
I'll close this since there haven't been any other cases (and the one above looks like a vera/device problem). Happy to re-open if we get more to work on.

**Comment by roflcoopter** [comment]
I am facing this issue with one door sensor and now one motion sensor. The motion sensor was working but for various reasons i wanted to exclude it then reinclude, but now the state doesnt update in home assistant anymore. The logs indicate nothing when the device is tripped
